# permissions for end users to view vnis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vni-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-learning
    app.kubernetes.io/part-of: operator-learning
    app.kubernetes.io/managed-by: kustomize
  name: vni-viewer-role
rules:
- apiGroups:
  - sdn.github.com
  resources:
  - vnis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sdn.github.com
  resources:
  - vnis/status
  verbs:
  - get
