apiVersion: sdn.github.com/v1
kind: Subnet
metadata:
  labels:
    app.kubernetes.io/name: subnet
    app.kubernetes.io/instance: subnet-sample
    app.kubernetes.io/part-of: operator-learning
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator-learning
  name: subnet-sample
spec:
  # TODO(user): Add fields here
